### PR TITLE
Add: missing x64 configuration Debug/Release

### PR DESCRIPTION
**Pull request by Blonder**

### CODE REVIEW

**Comment by david-maw** [comment]
Interesting, when I compile a 64 bit debug build on VS2017 I get:
`1>...\sslserver.cpp(207): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data`
Do you?

**Comment by Blonder** [comment]
> 
> 
> Interesting, when I compile a 64 bit debug build on VS2017 I get:
> `1>...\sslserver.cpp(207): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data`
> Do you?

Yes, this is because you pass a `size_t sizeof(readBuffer) - readBufferBytes - ((CHAR*)readPtr - &readBuffer[0])` into an `int` - second parameter of `m_SocketStream->Recv`.
You also set in the project properties of StreamServer "C/C++/General/Treat Warnings As Errors/Yes(/WX)" so you get an error C2220 in StreamServer Debug build additionally to the warning.

**Comment by david-maw** [comment]
Sorry, I wasn't clear. I understand why the warning occurred, just not why you created fixes for the others but not that particular one. I thought perhaps our configurations were different in some way so you hadn't seen it. Generally I like to leave /WX on so as to discourage people (me in this case) from ignoring warnings because they are often a sign that I've missed something.

**Comment by Blonder** [comment]
Ok, I understand that you want to keep the /WX setting, no problem, than we should enable it for x64 too.
You should also enable /WX for the Win32 Release configuration in the StreamServer.vcxproj.
Also the Warning Level of this project/configuration differs from the other settings /W3 instead of /W4.

**Comment by david-maw** [comment]
I think all the changes are in the master branch now, if you do too, then these pull requests can be closed.

**Pull request closed without merging**
