### PR TITLE
Stdafx.h to pch.h, framework.h and targetver.h

### PR DESCRIPTION
**Pull request by Blonder**
using new since Visual Studio 2017 pch.h, framework.h and targetver.h instead of deprecated stdafx.h

### CODE REVIEW

**Comment by david-maw** [comment]
I'm puzzled about the RecvInitiated case though I have not had time to study it closely - the original code was meant to address the case where the next message is slow to arrive, lets say it takes 5 seconds and the timeout is three. The idea was that the first call to RecvPartial would exit without receiving anything and (now) reporting timeout but leaving an asynchronous read still pending. The next call would wait on the same asynchronous read which this time would complete within the timeout period. That's not to say it actually works right, but that was the plan.

Incidentally, I don't think stdafx.h is deprecated, just not used in new projects.  Not that I object to using new style naming if that fits better with your coding conventions..

**Comment by Blonder** [comment]
> I'm puzzled about the RecvInitiated case though I have not had time to study it closely - the original code was meant to address the case where the next message is slow to arrive, lets say it takes 5 seconds and the timeout is three. The idea was that the first call to RecvPartial would exit without receiving anything and (now) reporting timeout but leaving an asynchronous read still pending. The next call would wait on the same asynchronous read which this time would complete within the timeout period. That's not to say it actually works right, but that was the plan.

In the calling while loop in RecvMsg you returned SOCKET_ERROR so you never came into RecvPartial again when a WSA_IO_PENDING occurred and the time timed out.

> Incidentally, I don't think stdafx.h is deprecated, just not used in new projects. Not that I object to using new style naming if that fits better with your coding conventions..

Not deprecated but not used any more in new projects:
https://docs.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=vs-2019
But I think for consistency and to make diff easier with future Visual Studio Versions we should use .pch.
I always do a compare of newly generated projects with my existing ones to see if there are new features added or removed or what has changed and update my projects. It makes life easier if the filenames are equal.

**Comment by david-maw** [comment]
Ah, I see the confusion - the problem is RecvMsg isn't the only caller of RecvPartial, though that fact is a lot clearer in CPassiveSock than CActiveSock. ReceiveBytes calls CPassiveSock::ReceivePartial so, in effect, for an unencrypted connection (or one where SSL has been stopped but the socket continues) user code can call ReceiveBytes any way it likes - in particular it can call again if there's a timeout.  I'm pretty sure that all the other callers give up if SOCKET_ERROR is returned. There's a lot of identical code and variables between CActiveSock and CPassiveSock and I'm beginning to wonder if I could collect it all into a new class which could become a common ancestor of both to avoid all the duplication.

**Comment by Blonder** [comment]
Yes, there is a lot of duplicate code it should be merged into one class.

**Comment by david-maw** [comment]
I merged in the changes - the project looks as I'd expect, but the history is a mess - still all the changes seem to be there which is a good thing. I don't have much experience managing a share project in Git, let alone GitHub, so I'm writing a lot of the complex history off to ignorance. That's all by way of a warning that if you notice something incorrect or absent it probably is not intentional!

**Comment by Blonder** [comment]
>... I don't have much experience managing a share project in Git, let alone GitHub, so I'm writing a lot of the complex history off to ignorance. That's all by way of a warning that if you notice something incorrect or absent it probably is not intentional!

No problem, everyone makes mistakes, me too. I think you have done a very good job in creating these classes and thanks for the idea and realizing it (Microsoft should have done this, the MFC is missing a lot of features), it helped me a lot in my work - the last commits were only 'polishing the last 10%'.

**Pull request closed without merging**
